### ISSUE TITLE
Missing Quick sort Algorithm

### ISSUE THREAD

**Issue by Chayandev** [tausiq2003/DSA-algorithms#10]
**Quick sort algorithm is missing , no algorithm & code is there for quick sort in any language. **

**Comment by Chayandev** [comment]
Please assign me this issue @tausiq2003 I want to work on this.

**Comment by tausiq2003** [comment]
You can contribute

**Comment by Naprila** [comment]
@tausiq2003  would like to add some more algorithm to Sorting Algorithm Section which are frequently used.

**Comment by Chayandev** [comment]
@tausiq2003 please add a label hacktoberfest accepted in this merge request , it will be very helpful to me.
